account/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    register_account,
    user_info,
    dashboard,
    money_transfer,
    confirm_transaction,
    change_pin,
    update_info,
)



urlpatterns = [
    path('join/register/', register_account, name='register'),
    path('join/user_info/', user_info, name="user_info"),
    path('pages/dashboard/', dashboard, name="dashboard"),
    path('transactions/money_transfer/', money_transfer, name='money_transfer'),
    path('transactions/confirm_transaction/', confirm_transaction, name="confirm_transaction"),
    path('pages/change_pin/', change_pin, name="change_pin"),
    path('pages/update_info/', update_info, name="update_info")
]
urlpatterns += static(settings.MEDIA_URL,
                            document_root = settings.MEDIA_ROOT)

bank_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

from account.views import home 

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('users/', include("users.urls")),
]
urlpatterns += static(settings.MEDIA_URL,
                            document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 

from .views import (
    login_request,
    logout_request,
    change_password,
)


urlpatterns = [
    path('join/login/', login_request, name="login"),
    path('join/logout/', logout_request, name="logout"),
    path('pages/change_password', change_password, name="change_password"),
]
urlpatterns += static(settings.MEDIA_URL,
                            document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
 



# account model 
class Account(models.Model):
    acc_type = (
        ('savings','savings'),
        ('checkings','checkings')
    )
    account_name = models.CharField(max_length=60, null=False, blank=False)
    account_number = models.CharField(max_length=20, null=False,blank=False)
    account_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_account")
    account_balance = models.IntegerField(default=0.00, null=False,blank=False)
    account_type = models.CharField(choices=acc_type, default='savings', max_length=20, null=False, blank=False)
    account_address = models.CharField(max_length=150, null=False,blank=False)
    account_phone = models.CharField(max_length=14, null=False, blank=False)
    account_occupation = models.CharField(max_length=60, null=False, blank=False)
    transaction_pin = models.CharField(max_length=6, null=False, blank=False)
    date_opened = models.DateField(auto_now_add=True)
    time_opened = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-time_opened']

    def __str__(self):
        return f"{self.account_number}"
    
# account history 
class Account_History(models.Model):
    account_history_owner = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="history_owner")
    sender_name= models.CharField(max_length=60, null=False, blank=False)
    reciever_account = models.ForeignKey(Account, on_delete=models.CASCADE,related_name="receiver")
    reciever_account_name = models.CharField(max_length=60, null=False,blank=False)
    transaction_type = models.CharField(max_length=50, null=False,blank=False)
    amount = models.CharField(max_length=30, null=True, blank=True)
    balance_before_transaction = models.IntegerField(null=False,blank=False)
    balance_after_transaction = models.IntegerField(null=False,blank=False)
    date = models.DateField(auto_now_add=True)
    time = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-time']


    def __str__(self):
        return f"{self.account_history_owner}"

account/forms.py
from django import forms 
from django.contrib.auth import get_user_model

from .models import Account

import re 

User = get_user_model()




""" Account form ... open account and register form """

# This form contains basic account information 
class AccountInformationForm(forms.Form):
    acc_type = (
        ('savings','savings'),
        ('checkings','checkings')
    )
    first_name = forms.CharField(max_length=30, min_length=2, required=True)
    last_name = forms.CharField(max_length=30, min_length=2, required=True)
    phone = forms.CharField(min_length=5, max_length=14, required=True)
    address = forms.CharField(max_length=80, required=True)
    occupation = forms.CharField(max_length=60, required=True)
    account_type = forms.CharField(max_length=20, required=True)

    """ cleaning form fields """

    #clean firstname
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name'].lower()
        
        if len(first_name) < 2 or len(first_name) > 30:
            raise forms.ValidationError("Name must be between 2 to 30 characters")
        
        if first_name == " ":
            raise forms.ValidationError("Name cannot be empty")
        
        if re.search(r"^[@_!#$%^&*()-<>?/\|}={+~:]", first_name):
            raise forms.ValidationError("Name cannot contain special characters")
        
        return first_name

    #clean lastname
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name'].lower()
        
        if len(last_name) < 2 or len(last_name) > 30:
            raise forms.ValidationError("Name must be between 2 to 30 characters")
        
        if last_name == " ":
            raise forms.ValidationError("Name cannot be empty")
        
        if re.search(r"^[@_!#$%^&*()-<>?/\|}={+~:]", last_name):
            raise forms.ValidationError("Name cannot contain special characters")
        
        return last_name

    #clean phone
    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        chk_phone = Account.objects.filter(account_phone=phone)

        if chk_phone.count():
            raise forms.ValidationError("A user with that phone number already exist")
        
        if re.search(r"^[@_!#$%^&*<>?/\|}={~:]", phone):
            raise forms.ValidationError("Phone can not contain special characters")

        if not all(t.isdigit() for t in phone):
            raise forms.ValidationError("Phone can only contian numbers")
        
        if len(phone) < 5 or len(phone) > 14:
            raise forms.ValidationError("Phone must be between 5 to 14 characters")
        
        if phone == " ":
            raise forms.ValidationError("Phone is required")
        
        return phone

    #clean address
    def clean_address(self):
        address = self.cleaned_data['address']
        
        if len(address) > 80:
            raise forms.ValidationError("Address cannot be more than 80 characters")
        
        if address == " ":
            raise forms.ValidationError("Address cannot be empty")
        
        if re.search(r"^[@!$%^&*()<>?/\|}={~:]", address):
            raise forms.ValidationError("Address cannot contain special characters")

        return address

    #clean occupation
    def clean_occupation(self):
        occupation = self.cleaned_data['occupation']
        
        if len(occupation) > 60:
            raise forms.ValidationError("Occupation cannot be more than 60 characters")
        
        if occupation == " ":
            raise forms.ValidationError("Occupation cannot be empty")
        
        if re.search(r"^[@_!$%^&*()<>?/\|}={+~:]", occupation):
            raise forms.ValidationError("Occupation cannot contain special characters")
        
        return occupation

    """ cleaning form fields end"""


# This form contains user information which will be used for further authentication 
class UserInformationForm(forms.Form):
    username = forms.CharField(min_length=5, max_length=20, required=True)
    email = forms.EmailField(min_length=6, max_length=60, required=True)
    password1 = forms.CharField(min_length=8, max_length=30,required=True,
                                widget=forms.PasswordInput)
    password2 = forms.CharField(min_length=8, max_length=30,required=True,
                                widget=forms.PasswordInput)
    transaction_pin = forms.CharField(min_length=4, max_length=6,required=True,
                                widget=forms.PasswordInput)


    """ cleaning form fields """

    # clean username 
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        chk_username = User.objects.filter(username = username)

        if chk_username.count():
            raise forms.ValidationError(f"Username {username} is unavailable")
        
        if username == " ":
            raise forms.ValidationError("Username cannot be empty")
        
        if len(username) < 5 or len(username) > 20:
            raise forms.ValidationError("Username must be between 4 to 20 characters")
        
        if re.search(r"^[@!#$%^&*()<>?/\|}={+~:]", username):
            raise forms.ValidationError("Only '_' and '-' are allowed in username. ")
        
        if " " in username.strip():
            username = username.replace(" ","_")

        return username
    
    # clean email 
    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        chk_email = User.objects.filter(email = email)

        if chk_email.count():
            raise forms.ValidationError(f"Email {email} is unavailable")
        
        if email == " ":
            raise forms.ValidationError("Email cannot be empty")
        
        if len(email) < 6 or len(email) > 60:
            raise forms.ValidationError("Email must be between 6 to 60 characters")
        
        return email
    

    # clean password
    def clean_password2(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 == " " or password2 == " ":
            raise forms.ValidationError("Password is required")
        
        if len(password1) < 8 or len(password1) > 30:
            raise forms.ValidationError("Password must be between 8 to 30 characters")

        if not re.search(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+$", password1):
            raise forms.ValidationError("Password must contain at least one uppercase, lowercase, digit and special character")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        
        return password2
    
    # clean transaction pin
    def clean_transaction_pin(self):
        transaction_pin = self.cleaned_data["transaction_pin"]

        if not re.search(r"^[@_!#$%^&*()-<>?/\|}={+~:]", transaction_pin):
            # raise forms.ValidationError("Transaction pin can not contain special characters")
            pass
        
        if not all(t.isdigit() for t in transaction_pin):
            raise forms.ValidationError("Transaction pin can only contian numbers")
        
        if len(transaction_pin) < 4 or len(transaction_pin) > 6:
            raise forms.ValidationError("Transaction pin must be between 4 to 6 characters")
        
        if transaction_pin == " ":
            raise forms.ValidationError("Transaction pin is required")

        return transaction_pin
    

    """ cleaning form fields ends """

""" Account form ... open account and register form  ends """


""" Money Transfer  form """
class TransferForm(forms.Form):
    account = forms.CharField(max_length=15, required=True)
    amount = forms.CharField(min_length=1, required=True)

    #clean account
    def clean_account(self):
        account = self.cleaned_data["account"]
        
        if not all(r.isdigit() for r in account):
            raise forms.ValidationError("Account number can only be numbers")

        if account == " ":
            raise forms.ValidationError("Account number cannot be empty")

        return account

 
    #clean amount
    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        
        if not all(r.isdigit() for r in amount):
            raise forms.ValidationError("Invalid amount")

        if amount == " ":
            raise forms.ValidationError("Amount cannot be empty")

        return amount


""" Money Transfer form ends """

""" change transaction pin """
class ChangePinForm(forms.Form):
    pin = forms.CharField(min_length=4, max_length=6, required=True)
    pin2 = forms.CharField(min_length=4, max_length=6, required=True)


    # clean transaction pin
    def clean_pin2(self):
        pin = self.cleaned_data["pin"]
        pin2 = self.cleaned_data["pin2"]

        if pin != pin2:
            raise forms.ValidationError("pin must match")
        
        if re.search(r"^[@_!#$%^&*()-<>?/\|}={+~:]", pin):
            raise forms.ValidationError("Transaction pin can not contain special characters")
        
        if not all(t.isdigit() for t in pin):
            raise forms.ValidationError("Transaction pin can only contian numbers")
        
        if len(pin) < 4 or len(pin) > 6:
            raise forms.ValidationError("Transaction pin must be between 4 to 6 characters")
        
        if pin == " " or pin2 == " ":
            raise forms.ValidationError("Transaction pin is required")

        return pin2
    

""" Update user information """
class UserInfoForm(forms.ModelForm):
    username = forms.CharField(min_length=5, max_length=20, required=True)
    email = forms.EmailField(min_length=6, max_length=60, required=True)

    class Meta:
        model = User 
        fields = ["username", "email"]

    # clean username 
    def clean_username(self):
        username = self.cleaned_data["username"].lower()
        # fetch current user
        user_username = self.instance.username

account/templates/pages/change_pin.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Pin -Axis Bank</title>
    <link href="{% static 'css/pages/change_pin.css' %}" rel="stylesheet">
</head>
<body>
    <div class="top-div">
        <h4>AXIS Bank</h4>

        <ul>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    <div class="intro">
        <p><b>Change Password</b></p>
    </div>
    <div class="change-password-div">
        <form method="post" action="{% url 'change_pin' %}">
            {% csrf_token %}
            <div class="inner-form-div">
                <label for="id_pin">New Pin:</label><br/>
                <input type="password" name="pin" placeholder="New Pin" maxlength="6" required id="id_pin"><br/>
                {{form.pin.errors}}<br/>
                <label for="id_pin2">Pin Again:</label><br/>
                <input type="password" name="pin2" placeholder="Pin Again" maxlength="6" required id="id_pin2"><br/>
                {{form.pin2.errors}}<br/>
                <button type="submit">Change Pin</button><br/><br/>

                <p> Changed your mind? go back to <a href="{% url 'dashboard' %}">Dashboard</a></p>
            </div>
        </form>
    </div>
</body>
</html>

{% endblock %}

account/templates/pages/dashboard.html
{% block content%}
{% load static %}
<!DOCTYPE html> 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/pages/dashboard.css' %}">
</head>
<body>
    {% if messages %}
    <ul class="messages">
        <!-- {% for message in messages %}
            {% for tag in message.tags %}
                {% if tag == "success" %}
                <p class="success">{{message}}</p>
                {% elif tag == "info" %}
                <p class="info">{{messages}}</p>
                {% else %}
                <p class="error">{{message}}</p>
                {% endif %}
            {% endfor %} -->

        <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        <!-- {% endfor %} -->
    {% endif %}
    <div class="top-div">
        <h4><span>Welcome,</span> {{request.user.username}}</h4>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a  class="logout" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    <div class="dashboard-div">
        <div class="profile-img">
            <img src="https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F7%2F7c%2FProfile_avatar_placeholder_large.png%3F20150327203541&tbnid=gp8LDHLwxDk-WM&vet=12ahUKEwiQqOKh9bOAAxUVrycCHebxAGAQMygNegUIARCSAg..i&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AProfile_avatar_placeholder_large.png&docid=xZyB11jLps67TM&w=360&h=360&q=profile%20image%20avatar&ved=2ahUKEwiQqOKh9bOAAxUVrycCHebxAGAQMygNegUIARCSAg"> 
        </div>
        {% for p in profile %}
        <div class="account-info">
            <p><b>Account Balance</b>: ${{p.account_balance}}</p>
            <p><b>Account Type</b>: {{p.account_type}}</p>
            <p><b>Account Number</b>: {{p.account_number}}</p>
        </div>
        <hr/><br/>
        <div class="profile-info">
            <p><b>Account Name</b>: {{p.account_name}}</p>
            <p><b>Username</b>: {{p.account_owner.username}}</p>
            <p><b>Email</b>: {{p.account_owner.email}}</p>
            <p><b>Phone</b>: {{p.account_phone}}</p>
            <p><b>Occupation</b>: {{p.account_occupation}}</p>
            <p><b>Address</b>: {{p.account_address}}</p>
        </div>
        {% endfor%}
        <div class="edit">
            <p><a href="{% url 'money_transfer' %}">Money Transfer</a></p> <p><a href="{% url 'update_info' %}">Edit user information</a></p> <p><a href="{% url 'change_password' %}">Change Password</a></p><p><a href="{% url 'change_pin' %}">Change Transaction Pin</a></p>
        </div>
    </div>
    <br/><br/><br/>
    <div class="bottom">
        <span>&copy; <i>AXIS BANK</i>, 2023</span>
    </div>
</body>
</html>

{% endblock %}

account/templates/pages/home.html
{% block content%}
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Axis Bank</title>
    <link rel="stylesheet" href="{% static 'css/pages/home.css' %}">
</head>
<body>
    <!-- <div class="top-div">
        {% if request.user.is_authenticated %}
        <h4><span>Welcome,</span> {{request.user.username}}</h4>
        <ul>
            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
            <li><a class="logout" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    {% else %}
    <div class="top-div">
        <h4>AXIS Bank</h4>
        <ul>
            <li><a class="login" href="{% url 'login' %}">LogIn</a></li>
            <li><a class="login" href="{% url 'register' %}">Register</a></li>
        </ul>
    </div> -->
    <!-- {% endif %} -->
    <div class="header-div">
        <div class="top-div">
            {% if request.user.is_authenticated %}
            <h4><span>Welcome,</span> {{request.user.username}}</h4>
            <ul>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a class="logout" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% else %}
        <div class="top-div">
            <h4>AXIS Bank</h4>
            <ul>
                <li><a class="login" href="{% url 'login' %}">LogIn</a></li>
                <li><a class="login" href="{% url 'register' %}">Register</a></li>
            </ul>
        </div>
        {% endif %}
        <h3 class="bnk">Banking Solution - Axis Bank</h3>
        <p class="bnk-2">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
    </div>
</body>
</html>

{% endblock %}

account/templates/pages/update_form.html
{% block content %} 
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Info -Axis Bank</title>
    <link href="{% static 'css/pages/update_form.css' %}" rel="stylesheet">
</head>
<body>
    <div class="top-div">
        <h4>AXIS Bank</h4>

        <ul>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
    <div class="intro">
        <p><b>Update Account Information</b></p>
    </div>
    <div class="update-form-div">
        <form method="post" action="{% url 'update_info' %}">
            {% csrf_token %}
            <div class="inner-form-div">
                {% csrf_token %}
                <label for="id_username">Username</label><br/>
                {{user_form.username}}<br/>
                {{form.username.errors}}<br/>
                <label for="id_email">Email</label><br/>
                {{user_form.email}}<br/>
                {{form.email.errors}}<br/>
                <label for="id_account_phone">Account phone</label><br/>
                {{profile_form.account_phone}}<br/>
                {{form.account_phone.errors}}<br/>
                <label for="id_account_address">Account address</label><br/>
                {{profile_form.account_address}}<br/>
                {{form.account_address.errors}}<br/>
                <label for="id_account_occupation">Account occupation</label><br/>
                {{profile_form.account_occupation}}<br/>
                {{form.account_occupation.errors}}<br/>
                <button type="submit">Update</button>
                <p> Changed your mind? go back to <a href="{% url 'dashboard' %}">Dashboard</a></p>
            </div>
        </form>
    </div>
</body>
</html>
{% endblock %}